BMI指数（即身体质量指数，简称体质指数又称体重，英文为Body Mass Index，简称BMI），是用体重公斤数除以身高米数平方得出的数字，是目前国际上常用的衡量人体胖瘦程度以及是否健康的一个标准。

In [1]:
height = [1, 2, 3, 4, 5]

weight = [6, 7, 8, 9, 10]

print(height/weight**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

List的挑战：
- 运算
- 速度

所有有了Numpy(Numeric Python)存在的理由。

In [5]:
import numpy as np

np_height = np.array([1, 2, 3, 4, 5])
np_weight = np.array([6, 7, 8, 9, 10])

bmi = np_height/np_weight ** 2

print(bmi)
print(type(bmi))

print(np_height + np_weight)

print(2*np_height)

[0.02777778 0.04081633 0.046875   0.04938272 0.05      ]
<class 'numpy.ndarray'>
[ 7  9 11 13 15]
[ 2  4  6  8 10]


In [7]:
# 均值描述的是集中趋势，而方差反映的是离散程度
import numpy as np

x = np.array([0, 8, 12, 20])
y = np.array([8, 9, 11, 12])

In [9]:
def variance(data):
    differences = data - np.mean(data)
    diff_sq = np.square(differences)
    variance = np.mean(diff_sq)
    return variance

def std(data):
    return np.sqrt(variance(data))
    
#print('mean:', np.mean(x), np.mean(y))
print('variance:', variance(x), variance(y))
#print('std:', std(x), std(y))

[ 0  8 12 20]
10.0
[-10.  -2.   2.  10.]
[100.   4.   4. 100.]
[ 8  9 11 12]
10.0
[-2. -1.  1.  2.]
[4. 1. 1. 4.]
variance: 52.0 2.5
